name = "TestingAeneas"
version = "0.1.0"
defaultTargets = ["testingaeneas"]

[[lean_lib]]
name = "TestingAeneas"

[[lean_exe]]
name = "testingaeneas"
root = "Main"

[[require]]
name = "aeneas"
path = "/home/ayhon/inria/aeneas/backends/lean"
